makeTestVerticies = ->
	verticies['A'] = new Vertex('A', 'a', [['C', 'B']], 1, 'B', 'graph1');
	verticies['B'] = new Vertex('B', 'b', [['C','K']], 1, 'D', 'graph1')
	verticies['C'] = new Vertex('C', 'c', [['A','F'],['L']], 2, 'E', 'graph1')
	verticies['D'] = new Vertex('D', 'd', [['E']], 1, 'G', 'graph1')
	verticies['E'] = new Vertex('E', 'e', [['F','J','I','H'],['Q']], 1, 'H', 'graph1')
	verticies['F'] = new Vertex('F', 'f', [['M']], 1, 'I', 'graph1')
	verticies['G'] = new Vertex('G', 'g', [['E']], 2, 'C', 'graph1')
	verticies['H'] = new Vertex('H', 'h', [['S','T']], 1, 'F', 'graph1')
	verticies['I'] = new Vertex('I', 'i', null, 1, 'V', 'graph1')
	verticies['J'] = new Vertex('J', 'j', [['Q']], 1, 'U', 'graph1')
	verticies['K'] = new Vertex('K', 'k', [['J']], 1, 'L', 'graph1')
	verticies['L'] = new Vertex('L', 'l', [['O']], 1, 'M', 'graph1')
	verticies['M'] = new Vertex('M', 'm', [['O']], 1, 'N', 'graph1')
	verticies['N'] = new Vertex('N', 'n', [['M']], 1, 'O', 'graph1')
	verticies['O'] = new Vertex('O', 'o', [['N']], 1, 'P', 'graph1')
	verticies['P'] = new Vertex('P', 'p', [['K']], 1, 'Q', 'graph1')
	verticies['Q'] = new Vertex('Q', 'q', [['P','R']], 1, 'R', 'graph1')
	verticies['R'] = new Vertex('R', 'r', [['S']], 1, 'S', 'graph1')
	verticies['S'] = new Vertex('S', 's', null, 1, 'T', 'graph1')
	verticies['T'] = new Vertex('T', 't', null, 1, null, 'graph1')
	verticies['U'] = new Vertex('U', 'u', [['V']], 1, 'K', 'graph1')
	verticies['V'] = new Vertex('V', 'v', [['U']], 1, 'J', 'graph1')


