// Generated by CoffeeScript 1.6.3
var makeTestVerticies, verticies;

verticies = {};

makeTestVerticies = function() {
  verticies = {};
  verticies['A'] = new Vertex('A', 'a', [['C', 'B']], 1, 'B');
  verticies['B'] = new Vertex('B', 'b', [['C', 'K']], 1, 'D');
  verticies['C'] = new Vertex('C', 'c', [['A', 'F'], ['L']], 2, 'E');
  verticies['D'] = new Vertex('D', 'd', [['E']], 1, 'G');
  verticies['E'] = new Vertex('E', 'e', [['F', 'J', 'I', 'H'], ['Q']], 1, 'H');
  verticies['F'] = new Vertex('F', 'f', [['M']], 1, 'I');
  verticies['G'] = new Vertex('G', 'g', [['E']], 2, 'C');
  verticies['H'] = new Vertex('H', 'h', [['S', 'T']], 1, 'F');
  verticies['I'] = new Vertex('I', 'i', null, 1, 'V');
  verticies['J'] = new Vertex('J', 'j', [['Q']], 1, 'U');
  verticies['K'] = new Vertex('K', 'k', [['J']], 1, 'L');
  verticies['L'] = new Vertex('L', 'l', [['O']], 1, 'M');
  verticies['M'] = new Vertex('M', 'm', [['O']], 1, 'N');
  verticies['N'] = new Vertex('N', 'n', [['M']], 1, 'O');
  verticies['O'] = new Vertex('O', 'o', [['N']], 1, 'P');
  verticies['P'] = new Vertex('P', 'p', [['K']], 1, 'Q');
  verticies['Q'] = new Vertex('Q', 'q', [['P', 'R']], 1, 'R');
  verticies['R'] = new Vertex('R', 'r', [['S']], 1, 'S');
  verticies['S'] = new Vertex('S', 's', null, 1, 'T');
  verticies['T'] = new Vertex('T', 't', null, 1, null);
  verticies['U'] = new Vertex('U', 'u', [['V']], 1, 'K');
  return verticies['V'] = new Vertex('V', 'v', [['U']], 1, 'J');
};
