// Generated by CoffeeScript 1.6.3
/* add all private attributes to spec by convention.*/

var telescopicText;

telescopicText = {};

telescopicText.graphs = {};

telescopicText.reset = function() {
  telescopicText.graphs = {};
  return telescopicText.graph({
    _name: 'telescopicDefaultID'
  });
};

telescopicText.graph = function(spec) {
  /* private*/

  var that, _nodes;
  that = {};
  _nodes = {};
  /* public*/

  that.getName = function() {
    return spec._name;
  };
  that.getNode = function(key) {
    var node;
    node = _nodes[key];
    if (node === void 0) {
      console.log('Graph "' + this.getName() + '" is missing a child, with key "' + key + '."');
      null;
    }
    return node;
  };
  that.setNode = function(key, value) {
    _nodes[key] = value;
    return that;
  };
  /* insert graph into graphs object*/

  telescopicText.graphs[spec._name] = that;
  return that;
};

telescopicText.vertex = function(spec) {
  /* constructor necessities*/

  var that;
  if (!telescopicText.graphs[spec._graph]) {
    spec._graph = telescopicText.graph({
      _name: spec._graph
    });
  } else {
    spec._graph = telescopicText.graphs[spec._graph];
  }
  /* private attributes*/

  that = {};
  spec._previous = null;
  spec._click_count = 0;
  /* public attributes*/

  that.content = spec.content;
  /* public functions*/

  that.getStarter = function() {
    return spec._starter;
  };
  that.getName = function() {
    return spec._name;
  };
  that.getGraph = function() {
    return spec._graph;
  };
  that.getNext = function() {
    return spec._next;
  };
  that.setNext = function(newNext) {
    return spec._next = newNext;
  };
  that.getPrevious = function() {
    return spec._previous;
  };
  that.setPrevious = function() {
    return spec._previous = newPrevious;
  };
  that.getClickCount = function() {
    return spec._click_count;
  };
  that.getChildren = function() {
    return spec._children || [];
  };
  /* public functions meta info*/

  that.getRemainAfterClick = function() {
    return spec._remain_after_click;
  };
  that.findClicksRemaining = function() {
    /* ignore _remain_after_click b/c it's not a click*/

    return that.children.length - spec._click_count;
  };
  return that;
};
