// Generated by CoffeeScript 1.6.3
test('forward click a node. Does the node change attributes appropriately?', function() {
  var graph1, vertex_A;
  telescopicText.reset();
  graph1 = makeTestVerticies();
  vertex_A = graph1.getNode('A');
  vertex_A.forward_click();
  equal(vertex_A.findClicksRemaining(), 0);
  return equal(vertex_A.shouldBeVisible(), false);
});
