// Generated by CoffeeScript 1.6.3
test('find clicks remaining on unclickable link', function() {
  var vertexX;
  telescopicText.reset();
  vertexX = telescopicText.vertex({});
  equal(vertexX.getClickCount(), 0);
  return equal(vertexX.findClicksRemaining(), 0);
});

test('forward click a node, vertex_A. Test vertex_A visibility and clicks remaining', function() {
  var graph1;
  telescopicText.reset();
  graph1 = makeTestVerticies();
  equal(vertexA.findClicksRemaining(), 1);
  vertexA.forwardClick();
  equal(vertexA.findClicksRemaining(), 0);
  return equal(vertexA.shouldBeVisible(), false);
});
