// Generated by CoffeeScript 1.6.3
test('vertex sets child references on command', function() {
  telescopicText.reset();
  makeTestVerticies();
  vertexA.setChildrenReferences();
  equal(vertexA.getChildren()[0][0], vertexC);
  equal(vertexA.getChildren()[0][1], vertexB);
  return equal(vertexA.getChildren()[1], void 0);
});
