// Generated by CoffeeScript 1.6.3
var makeDefaultVertex1, makeDefaultVertex2;

test('graphs generate on reset', function() {
  telescopicText.reset();
  return ok(telescopicText.graphs['telescopicDefaultID']);
});

test('Verticies public spec attributes are visible', function() {
  var nameVertex;
  telescopicText.reset();
  nameVertex = makeDefaultVertex1();
  return equal(nameVertex.content, 'myContent');
});

test('Verticies private spec attributes have getters and setters', function() {
  var nameVertex;
  nameVertex = makeDefaultVertex1();
  equal(nameVertex.getName(), 'myName');
  equal(nameVertex.getRemainAfterClick(), true);
  equal(nameVertex.getNext(), true);
  nameVertex.setNext(false);
  equal(nameVertex.getNext(), false);
  equal(nameVertex.getStarter(), true);
  return ok(nameVertex.getChildren() instanceof Array);
});

test('Vertex attributes default correctly.', function() {
  var nameVertex;
  nameVertex = makeDefaultVertex2();
  ok(nameVertex.getChildren() instanceof Array);
  return equal(nameVertex.getChildren()[0], void 0);
});

test('Make sure verticies create a graph and insert themselves into it on creation', function() {
  var nameVertex;
  nameVertex = makeDefaultVertex1();
  equal(telescopicText.graphs['defaultID2'].getName(), 'defaultID2');
  return equal(nameVertex.getGraph().getName(), 'defaultID2');
});

makeDefaultVertex1 = function() {
  var nameVertexSpec;
  nameVertexSpec = {
    _name: 'myName',
    content: 'myContent',
    _children: [],
    _remain_after_click: true,
    _next: true,
    _graph: 'defaultID2',
    _starter: true
  };
  return telescopicText.vertex(nameVertexSpec);
};

makeDefaultVertex2 = function() {
  var nameVertexSpec;
  nameVertexSpec = {
    _name: 'myName',
    content: 'myContent',
    _next: true
  };
  return telescopicText.vertex(nameVertexSpec);
};
