// Generated by CoffeeScript 1.6.3
test('linked list appears on page.', function() {
  var graph1;
  telescopicText.reset();
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  return ok($('#tText-graph1').children().length > 0);
});

test('nodes are hidden and shown appropriately', function() {
  var graph1;
  telescopicText.reset();
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  equal($('#tText_A').is(':visible'), true, 'starter nodes are visible');
  equal($('#tText_D').is(':visible'), true);
  equal($('#tText_G').is(':visible'), true);
  equal($('#tText_V').is(':visible'), true);
  equal($('#tText_B').is(':visible'), false, 'non-starter nodes are not visible');
  equal($('#tText_E').is(':visible'), false);
  equal($('#tText_Z').length, 0, 'markup nodes are not on the page');
  return equal($('#tText_Y').length, 0);
});

test('appropriate nodes dissapear, reappear after forwardClick()', function() {
  var graph1;
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  vertexA.forwardClick();
  equal($('#tText_A').is(':visible'), false, 'A is not visible after click');
  equal($('#tText_B').is(':visible'), true, 'B appears after A click');
  return equal($('#tText_C').is(':visible'), true, 'C appears after A click');
});

test('verticies are wrapped after foward click', function() {
  var graph1;
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  vertexA.forwardClick();
  vertexC.forwardClick();
  return equal(1, 1);
});

test('user clicks an individual vertex', function() {
  var graph1;
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  $('#tText_A').click();
  equal($('#tText_A').is(':visible'), false);
  equal($('#tText_B').is(':visible'), true);
  return equal($('#tText_C').is(':visible'), true);
});

test('graph.forward is false when alt downkey', function() {
  var e, graph1;
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  equal(telescopicText.forward, true);
  e = jQuery.Event("keydown");
  e.altKey = true;
  $(document).trigger(e);
  return equal(telescopicText.forward, false);
});

test('graph.forward is true when alt keyup', function() {
  var e, graph1;
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  telescopicText.forward = false;
  e = jQuery.Event("keyup");
  e.altKey = true;
  $(document).trigger(e);
  return equal(telescopicText.forward, true);
});

test('verticies are correctly highlighted during keydown', function() {
  var e, graph1;
  telescopicText.reset();
  graph1 = makeTestVerticies().setGraphChildReferences().makeLinkedList(vertexA);
  $('#tText_A').click();
  equal(telescopicText.forward, true);
  e = jQuery.Event("keydown");
  e.altKey = true;
  $(document).trigger(e);
  ok($('#tText_B').hasClass('tText_backClickable'));
  return equal($('#tText_A').is(':visible'), false);
});
