// Generated by CoffeeScript 1.6.3
test('Verticies have the correct attributes', function() {
  var name_vertex;
  name_vertex = new telescopicText.Vertex('myName', 'myContent', null, null, null, null);
  equal(name_vertex.getName(), 'myName');
  equal(name_vertex.content, 'myContent');
  ok(name_vertex.children instanceof Array && name_vertex.children[0] instanceof Array);
  ok(name_vertex.children[0][0] === void 0);
  equal(name_vertex.getRemainAfterClick(), false);
  equal(name_vertex.getNext(), null);
  equal(name_vertex.getGraph().getName(), 'telescopicDefaultID');
  equal(name_vertex.tree_edge, null);
  equal(name_vertex.forward_edge, null);
  equal(name_vertex.back_edge, null);
  equal(name_vertex.cross_edge, null);
  name_vertex = new telescopicText.Vertex('myName', 'myContent', [['foo'], ['bar']], true, 'next', 'newGraphName');
  equal(name_vertex.children[0][0], 'foo');
  equal(name_vertex.children[1][0], 'bar');
  equal(name_vertex.getRemainAfterClick(), true);
  equal(name_vertex.getNext(), 'next');
  equal(name_vertex.getGraph().getName(), 'newGraphName');
  telescopicText.graphs = {};
  return new telescopicText.Graph('telescopicDefaultID');
});

test('Verticies create the new relevant graph and insert themselves', function() {
  var bar, foo;
  foo = new telescopicText.Vertex("foo", null, null, true, null, null);
  equal(telescopicText.graphs['telescopicDefaultID'].getName(), 'telescopicDefaultID');
  equal(telescopicText.graphs['telescopicDefaultID'].getNode('foo'), foo);
  bar = new telescopicText.Vertex("bar", null, null, true, null, 'myGraph');
  equal(telescopicText.graphs['myGraph'].getName(), 'myGraph');
  equal(telescopicText.graphs['myGraph'].getNode('bar'), bar);
  telescopicText.graphs = {};
  return new telescopicText.Graph('telescopicDefaultID');
});

test('Vertex.setChildReferences references correct graph, and verticies', function() {
  var vertex_A, vertex_B, vertex_C, vertex_D;
  vertex_A = new telescopicText.Vertex('A', 'a', [['D'], ['B', 'C', 'nope']], null, 'B', null);
  vertex_B = new telescopicText.Vertex('B', 'b', null, true, null, null);
  vertex_C = new telescopicText.Vertex('C', 'c', null, null, null, null);
  vertex_D = new telescopicText.Vertex('D', 'd', null, null, null, null);
  vertex_A.setChildrenReferences();
  equal(vertex_A.children[0][0], vertex_D);
  equal(vertex_A.children[1][0], vertex_B);
  equal(vertex_A.children[1][1], vertex_C);
  equal(vertex_A.children[1][2], void 0);
  telescopicText.graphs = {};
  return new telescopicText.Graph('telescopicDefaultID');
});

test('telescopicText.Graph makeLinkedList', function() {
  var vertex_A, vertex_B, vertex_C;
  vertex_A = new telescopicText.Vertex('A', 'a', null, null, 'B', null);
  vertex_B = new telescopicText.Vertex('B', 'b', null, true, 'C', null);
  vertex_C = new telescopicText.Vertex('C', 'c', null, null, null, null);
  telescopicText.graphs['telescopicDefaultID'].makeLinkedList(vertex_A);
  equal(vertex_A.getNext(), vertex_B);
  equal(vertex_B.getNext(), vertex_C);
  equal(vertex_C.getNext(), null);
  equal(vertex_A.getPrevious(), null);
  equal(vertex_B.getPrevious(), vertex_A);
  equal(vertex_C.getPrevious(), vertex_B);
  return equal('foo', foo);
});
